language: r
cache: packages

script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt install r-bas*
  - which R
  - whereis R
  - which Rscript
  - whereis Rscript
  - export PATH="$PATH:/home/travis/R-bin/bin/Rscript"
  - sudo scripts/install_razzo.sh
  - mkdir data
  - cd data
  - ./../scripts/create_parameter_files.sh

after_success:
  - cd data; find .