language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - xl0418/dododo
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/babette
  - richelbilderbeek/beastier
  - ropensci/beautier
  - richelbilderbeek/mauricer
  - richelbilderbeek/pirouette
  - richelbilderbeek/razzo@richel
  - richelbilderbeek/tracerer
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling
  - Giappo/mbd

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev

before_script:
  - Rscript -e 'devtools::install_github("xl0418/dododo")'

script:
  # Java
  #- sudo apt-get install -qq oracle-java8-installer # Java 8
  #- sudo apt-get install oracle-java8-set-default
  - ./scripts/1_install_razzo.sh
  - ./scripts/2_create_parameter_files.sh
  - ./scripts/3_create_input_files.sh
  - # No need to install BEAST2: this is done by 1
  - ./scripts/4_create_posterior_files.sh
  - ./scripts/5_create_nltt_files.sh
  - # No need to install NS: this is done by 1
  - ./scripts/6_create_marg_lik_files.sh
  - ./scripts/7_create_nltt_stats_file.sh
  - ./scripts/8_create_esses_files.sh
  - ./scripts/9_create_marg_liks_file.sh
  - ./scripts/10_create_fig_1_file.sh

after_success:
  - pwd
  - cd data; find .; cd ..
  - cd results; find .; cd ..
  - cat $(find . | egrep "results.*\.csv$")

after_failure:
  - pwd
  - cd data; find .; cd ..
  - cd results; find .; cd ..
  - cat $(find . | egrep "results.*\.csv$")
