language: r
cache: packages

# Don't! Use scripts/install_packages to install R packages
# r_packages:
#   - devtools
#   - ggplot2
#   - hunspell
#   - xml2

# Don't! Use scripts/install_packages to install R packages
# r_github_packages:
#   - jimhester/covr
#   - jimhester/lintr
#   - MangoTheCat/goodpractice
#   - ropensci/spelling
#   - richelbilderbeek/beautier
#   - richelbilderbeek/beastier
#   - richelbilderbeek/tracerer
#   - richelbilderbeek/babette
#   - richelbilderbeek/pirouette
#   - richelbilderbeek/razzo
#   - Giappo/mbd

# Nope, everything should be done in the scripts
# before_script:
  # - sudo apt-get install -qq oracle-java8-installer # Java 8
  # - sudo apt-get install oracle-java8-set-default
  # - Rscript -e "beastier::install_beast2()"
  # - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  # - sudo pip install proselint

script:
  - sudo apt-get install -qq oracle-java8-installer # Java 8

after_success:
  - cd data; find .