language: r
cache: packages

r_github_packages:
  - r-lib/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling
  - richelbilderbeek/mcbette@v1.8
  - thijsjanzen/nodeSub@v0.4.2
  - richelbilderbeek/pirouette@v1.6.2
  - richelbilderbeek/peregrine@v1.0
  - Giappo/mbd@v1.0
  - Giappo/mbd.SimTrees@v0.1
  - richelbilderbeek/becosys@v1.0.1
  - richelbilderbeek/raztr@v1.0
  - richelbilderbeek/razzo@richel


before_install:
  - echo $TRAVIS_R_VERSION_STRING
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  # Install packages
  #- ./scripts/1_install_razzo.sh

before_script:
  - Rscript -e 'if (!beastier::is_beast2_installed()) beastier::install_beast2()'
  - Rscript -e 'if (!mauricer::is_beast2_pkg_installed("NS")) mauricer::install_beast2_pkg("NS")'

script:
  - rm -rf data
  - rm -rf results
  - ./scripts/regen_data.sh

after_success:
  - pwd
  - cd data; find .; cd ..
  - cd results; find .; cd ..
  - # cat $(find . | egrep "results.*\.csv$")
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

after_failure:
  - pwd
  - cd data; find .; cd ..
  - cd results; find .; cd ..
  - # cat $(find . | egrep "results.*\.csv$")
  # Download thesis
  - wget https://pure.rug.nl/ws/files/132028374/Complete_thesis.pdf

