language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/babette
  - richelbilderbeek/beastier
  - richelbilderbeek/beautier
  - richelbilderbeek/mauricer
  - richelbilderbeek/pirouette
  - richelbilderbeek/razzo@richel
  - richelbilderbeek/tracerer
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling
  - Giappo/mbd

script:
  # Java
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - ./scripts/1_install_razzo.sh
  - # Rscript -e "beastier::install_beast2()"
  - # Rscript -e 'mauricer::mrc_install("NS")'
  - ./scripts/2_create_parameter_files.sh
  - ./scripts/3_create_input_files.sh
  - ./scripts/4_create_posterior_files.sh
  - ./scripts/5_create_nltt_files.sh
  - # ./scripts/6_create_marg_lik_files.sh

after_success:
  - pwd
  - cd data; find .; cd ..
  - cd results; find .; cd ..

after_failure:
  - pwd
  - cd data; find .; cd ..
  - cd results; find .; cd ..
