language: r
cache: packages






before_script:
  #- sudo apt install r-base r-base-core r-base-dev
  - sudo add-apt-repository -y "ppa:marutter/rrutter"
  - sudo apt-get update -qq
  - export PATH="$PATH:/home/travis/R-bin/bin"
  - echo $PATH

script:
  - which R
  - whereis R
  - which Rscript
  - whereis Rscript
  - echo $PATH
  - sudo ./scripts/install_razzo.sh
  - mkdir data
  - cd data
  - export PATH="$PATH:/home/travis/R-bin/bin"; ./../scripts/create_parameter_files.sh

after_success:
  - cd data; find .