language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - KlausVigo/phangorn
  - Giappo/mbd
  - ropensci/beautier
  - ropensci/tracerer
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/nLTT
  - richelbilderbeek/mcbette
  - richelbilderbeek/pirouette@richel
  - richelbilderbeek/razzo@richel
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  - sudo apt install -qq libmpfr-dev

script:
  # Java
  #- sudo apt-get install -qq oracle-java8-installer # Java 8
  #- sudo apt-get install oracle-java8-set-default
  - ./scripts/1_install_razzo.sh
  - ./scripts/2_create_parameter_files.sh
  - # No need to install BEAST2, nor NS: this is done by 1
  - ./scripts/3_run_razzo.sh
  - #./scripts/7_create_nltt_stats_file.sh
  - #./scripts/8_create_esses_files.sh
  - #./scripts/9_create_marg_liks_file.sh
  - #./scripts/10_create_fig_1_file.sh

after_success:
  - pwd
  - cd data; find .; cd ..
  - cd results; find .; cd ..
  - # cat $(find . | egrep "results.*\.csv$")

after_failure:
  - pwd
  - cd data; find .; cd ..
  - cd results; find .; cd ..
  - # cat $(find . | egrep "results.*\.csv$")
