language: r
cache: packages

script:
  - whereis Rscript
  - export PATH="$PATH:/home/travis/R-3.1.2/bin/"
  - sudo scripts/install_razzo.sh
  - mkdir data
  - cd data
  - ./../scripts/create_parameter_files.sh

after_success:
  - cd data; find .