language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/babette
  - richelbilderbeek/beastier
  - richelbilderbeek/beautier
  - richelbilderbeek/mauricer
  - richelbilderbeek/pirouette
  - richelbilderbeek/razzo
  - richelbilderbeek/tracerer
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling
  # - Giappo/mbd # Don't use before overhaul is finished


script:
  # Use mbd package before overhaul
  - Rscript -e 'devtools::install_github("Giappo/mbd", ref = "d1b85b44cbcc28c20376708d8b6dee87298fa43d")'
  - ./scripts/create_parameter_files.sh
  - ./scripts/create_input_files.sh
  # Java
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - Rscript -e "beastier::install_beast2()"
  - ./scripts/create_posterior_files.sh
  - ./scripts/create_nltt_files.sh

after_success:
  - pwd
  - cd data; find .

after_failure:
  - pwd
  - cd data; find .
