sudo: true

script:
  - sudo apt install r-base
  - sudo scripts/install_razzo.sh
  - mkdir data
  - cd data
  - ./../scripts/create_parameter_files.sh

after_failure:
  - cd data; find .

after_success:
  - cd data; find .